name: itinerme
description: "A new Flutter project."

publish_to: 'none'


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.6.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.11.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.1
  cupertino_icons: ^1.0.8
  geocoding: ^2.1.0
  google_place: ^0.4.7
  url_launcher: ^6.2.5
  firebase_storage: ^11.7.7
  image_picker: ^0.8.7
  calendar_date_picker2: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env